### PR TITLE
fix: dial self

### LINKED ISSUE #326: Switch allows dial itself
Discovery modules can emit `PeerInfo` objects with multiaddrs that **do not** have the peer ID encapsulated.

A libp2p node's own peer info seems to have multiaddrs that **do** have the peer ID encapsulated.

It means that a libp2p node will attempt to dial itself because the following test will fail, when attempting to `decapsulate` `/ip4/127.0.0.1/tcp/4002` from the peer's own address `/ip4/127.0.0.1/tcp/4002/ipfs/QmebzNV1kSzLfaYpSZdShuiABNUxoKT1vJmCdxM2iWsM2j`:

https://github.com/libp2p/js-libp2p-switch/blob/828e685e79a918831a6dac0a868d0b209dd5874c/src/transport.js#L212-L220

refs https://github.com/libp2p/js-libp2p/issues/323

### PR DESCRIPTION
**Pull request by alanshaw**
This PR fixes multiple cases where a node would dial itself.

fixes #326

### CODE REVIEW

File: src/transport.js [hunk 1]
```diff
@@ -203,23 +203,61 @@ class TransportManager {
...
 
     const transportAddrs = transport.filter(multiaddrs)
-    if (!peerInfo) {
+    if (!peerInfo || !transportAddrs.length) {
       return transportAddrs
     }
 
-    const ourAddrs = peerInfo.multiaddrs.toArray()
-    return transportAddrs.filter((addr) => {
+    const ourAddrs = ourAddresses(peerInfo)
```
Comment (jacobheun) [inline src/transport.js:210]: I'm wondering if we should create and store this after listening is done, instead of running it before every dial. Our addresses shouldn't change, at the moment, after listening is done. It might save us quite a bit of processing when there are a lot of dials being done.

Comment (alanshaw) [reply src/transport.js:210]: I guess we could. It sounds like it would add a bunch of complexity that might easily cause confusion/bugs in the in the future if/when our addresses can change. Can we do it in a separate PR if it's a bottleneck?

Really, a lot of this should go away when addrs don't automatically carry a peer ID.

Comment (vasco-santos) [reply src/transport.js:210]: I am ok with addressing this in a new PR

**Review by vasco-santos — APPROVED** [review]
LGTM!

File: src/transport.js (hunk 1 above)
Comment (jacobheun) [reply src/transport.js:210]: > Really, a lot of this should go away when addrs don't automatically carry a peer ID.

That's true, and since it's on my list of things to get to this quarter I think we can move forward with this. The queuing should mitigate the performance impact anyway.

**Review by jacobheun — APPROVED** [review]

**Comment by achingbrain** [comment]
This sounds a bit like the issue I described in libp2p/js-libp2p-floodsub#58 - maybe this has fixed that too

**Comment by vasco-santos** [comment]
Can you check if that got fixed @achingbrain ?
